import { User, Skill, Service, TimeCredit, Booking, Transaction, Review, UserSkill } from '../types';

export const mockSkills: Skill[] = [
  { id: '1', name: 'Web Development', category: 'Technology' },
  { id: '2', name: 'Graphic Design', category: 'Design' },
  { id: '3', name: 'Cooking', category: 'Food & Beverage' },
  { id: '4', name: 'Language Teaching', category: 'Education' },
  { id: '5', name: 'Photography', category: 'Creative' },
  { id: '6', name: 'Music Lessons', category: 'Arts' },
  { id: '7', name: 'Home Repair', category: 'Services' },
  { id: '8', name: 'Fitness Training', category: 'Health' },
  { id: '9', name: 'Gardening', category: 'Services' },
  { id: '10', name: 'Writing & Editing', category: 'Professional' },
];

export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'sarah@example.com',
    username: 'sarah_dev',
    bio: 'Full-stack developer with 5 years of experience. Love to teach and learn new skills!',
    avatar_url: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=200',
    phone: '+1-555-0101',
    reputation_score: 4.8,
    total_reviews: 12,
    created_at: new Date('2024-01-15').toISOString(),
    level: 3,
    experience_points: 450,
    services_completed: 9,
    custom_credits_enabled: false,
  },
  {
    id: 'user-2',
    email: 'mike@example.com',
    username: 'mike_chef',
    bio: 'Professional chef offering cooking lessons. Specializing in Italian and French cuisine.',
    avatar_url: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=200',
    reputation_score: 4.9,
    total_reviews: 18,
    created_at: new Date('2024-02-01').toISOString(),
    level: 5,
    experience_points: 1250,
    services_completed: 25,
    custom_credits_enabled: true,
  },
  {
    id: 'user-3',
    email: 'emma@example.com',
    username: 'emma_design',
    bio: 'Graphic designer passionate about branding and visual storytelling.',
    avatar_url: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=200',
    reputation_score: 4.7,
    total_reviews: 9,
    created_at: new Date('2024-02-20').toISOString(),
    level: 2,
    experience_points: 200,
    services_completed: 4,
    custom_credits_enabled: false,
  },
  {
    id: 'user-4',
    email: 'john@example.com',
    username: 'john_photo',
    bio: 'Photographer and videographer. Offering portrait and event photography services.',
    avatar_url: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=200',
    reputation_score: 4.6,
    total_reviews: 7,
    created_at: new Date('2024-03-05').toISOString(),
    level: 4,
    experience_points: 850,
    services_completed: 17,
    custom_credits_enabled: false,
  },
  {
    id: 'current-user',
    email: 'demo@timebank.com',
    username: 'demo_user',
    bio: 'New to TimeBank! Excited to exchange skills and learn from the community.',
    avatar_url: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=200',
    phone: '+1-555-DEMO',
    reputation_score: 5.0,
    total_reviews: 2,
    created_at: new Date().toISOString(),
    level: 1,
    experience_points: 50,
    services_completed: 1,
    custom_credits_enabled: false,
  },
  {
    id: 'official-account',
    email: 'official@timebank.com',
    username: 'timebank_official',
    bio: 'Official TimeBank account offering verified professional services to help you get started.',
    avatar_url: 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=200',
    reputation_score: 5.0,
    total_reviews: 25,
    created_at: new Date('2024-01-01').toISOString(),
    phone: '+1-555-0100',
    level: 7,
    experience_points: 5500,
    services_completed: 100,
    custom_credits_enabled: true,
  },
  {
    id: 'level5-demo',
    email: 'level5@timebank.com',
    username: 'time_master_demo',
    bio: 'Level 5 Time Master - I have unlocked custom pricing! Offering premium services with competitive rates.',
    avatar_url: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=200',
    phone: '+1-555-LEVEL5',
    reputation_score: 4.8,
    total_reviews: 28,
    created_at: new Date('2024-01-10').toISOString(),
    level: 5,
    experience_points: 1250,
    services_completed: 25,
    custom_credits_enabled: true,
  },
  {
    id: 'level7-demo',
    email: 'level7@timebank.com',
    username: 'time_immortal_demo',
    bio: 'Level 7 Time Immortal - Elite provider with maximum perks and legendary status. Mentoring available!',
    avatar_url: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=200',
    phone: '+1-555-LEVEL7',
    reputation_score: 5.0,
    total_reviews: 82,
    created_at: new Date('2023-12-01').toISOString(),
    level: 7,
    experience_points: 6500,
    services_completed: 95,
    custom_credits_enabled: true,
  },
];

export const mockUserSkills: UserSkill[] = [
  { id: '1', user_id: 'user-1', skill_id: '1', type: 'offered', proficiency_level: 'expert' },
  { id: '2', user_id: 'user-1', skill_id: '3', type: 'needed', proficiency_level: 'beginner' },
  { id: '3', user_id: 'user-2', skill_id: '3', type: 'offered', proficiency_level: 'expert' },
  { id: '4', user_id: 'user-2', skill_id: '1', type: 'needed', proficiency_level: 'beginner' },
  { id: '5', user_id: 'user-3', skill_id: '2', type: 'offered', proficiency_level: 'expert' },
  { id: '6', user_id: 'user-3', skill_id: '5', type: 'needed', proficiency_level: 'intermediate' },
  { id: '7', user_id: 'user-4', skill_id: '5', type: 'offered', proficiency_level: 'expert' },
  { id: '8', user_id: 'current-user', skill_id: '10', type: 'offered', proficiency_level: 'intermediate' },
  { id: '9', user_id: 'official-account', skill_id: '1', type: 'offered', proficiency_level: 'expert' },
  { id: '10', user_id: 'official-account', skill_id: '6', type: 'offered', proficiency_level: 'expert' },
  { id: '11', user_id: 'official-account', skill_id: '8', type: 'offered', proficiency_level: 'expert' },
];

export const mockTimeCredits: TimeCredit[] = [
  {
    id: '1',
    user_id: 'user-1',
    balance: 15.5,
    total_earned: 45.0,
    total_spent: 29.5,
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    user_id: 'user-2',
    balance: 22.0,
    total_earned: 60.0,
    total_spent: 38.0,
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    user_id: 'user-3',
    balance: 18.5,
    total_earned: 38.5,
    total_spent: 20.0,
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    user_id: 'user-4',
    balance: 12.0,
    total_earned: 28.0,
    total_spent: 16.0,
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    user_id: 'current-user',
    balance: 10.0,
    total_earned: 10.0,
    total_spent: 0,
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    user_id: 'official-account',
    balance: 50.0,
    total_earned: 100.0,
    total_spent: 50.0,
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    user_id: 'level5-demo',
    balance: 35.0,
    total_earned: 80.0,
    total_spent: 45.0,
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    user_id: 'level7-demo',
    balance: 120.0,
    total_earned: 250.0,
    total_spent: 130.0,
    updated_at: new Date().toISOString(),
  },
];

export const mockServices: Service[] = [
  {
    id: 's-1',
    provider_id: 'user-1',
    skill_id: '1',
    title: 'React & TypeScript Development Help',
    description: 'I can help you build modern web applications using React and TypeScript. Perfect for beginners or intermediate developers.',
    credits_per_hour: 1.0,
    status: 'active',
    type: 'offer',
    created_at: new Date('2024-03-10').toISOString(),
  },
  {
    id: 's-2',
    provider_id: 'user-2',
    skill_id: '3',
    title: 'Italian Cooking Lessons',
    description: 'Learn to cook authentic Italian dishes from scratch. From pasta to risotto to tiramisu!',
    credits_per_hour: 1.0,
    status: 'active',
    type: 'offer',
    created_at: new Date('2024-03-12').toISOString(),
  },
  {
    id: 's-3',
    provider_id: 'user-3',
    skill_id: '2',
    title: 'Logo Design & Brand Identity',
    description: 'Create a professional logo and brand identity for your business or project.',
    credits_per_hour: 1.0,
    status: 'active',
    type: 'offer',
    created_at: new Date('2024-03-15').toISOString(),
  },
  {
    id: 's-4',
    provider_id: 'user-4',
    skill_id: '5',
    title: 'Portrait Photography Session',
    description: 'Professional portrait photography for individuals, families, or teams.',
    credits_per_hour: 1.0,
    status: 'active',
    type: 'offer',
    created_at: new Date('2024-03-18').toISOString(),
  },
  {
    id: 's-5',
    provider_id: 'user-1',
    skill_id: '3',
    title: 'Looking for Cooking Instructor',
    description: 'Want to learn basic cooking skills and meal preparation techniques.',
    credits_per_hour: 1.0,
    status: 'active',
    type: 'request',
    created_at: new Date('2024-03-20').toISOString(),
  },
  {
    id: 's-6',
    provider_id: 'official-account',
    skill_id: '1',
    title: 'Professional Web Development Mentoring',
    description: 'Get expert guidance on modern web development practices, including React, TypeScript, and best practices.',
    credits_per_hour: 1.5,
    status: 'active',
    type: 'offer',
    created_at: new Date('2024-03-22').toISOString(),
  },
  {
    id: 's-7',
    provider_id: 'official-account',
    skill_id: '6',
    title: 'Music Theory and Piano Lessons',
    description: 'Professional music instruction covering theory, technique, and repertoire for all skill levels.',
    credits_per_hour: 1.2,
    status: 'active',
    type: 'offer',
    created_at: new Date('2024-03-23').toISOString(),
  },
  {
    id: 's-8',
    provider_id: 'official-account',
    skill_id: '8',
    title: 'Personal Fitness Training',
    description: 'Certified personal trainer offering customized workout plans and nutrition guidance.',
    credits_per_hour: 1.3,
    status: 'active',
    type: 'offer',
    created_at: new Date('2024-03-24').toISOString(),
  },
];

export const mockBookings: Booking[] = [
  {
    id: 'b-1',
    service_id: 's-2',
    provider_id: 'user-2',
    requester_id: 'current-user',
    scheduled_start: new Date('2024-04-05T14:00:00').toISOString(),
    scheduled_end: new Date('2024-04-05T16:00:00').toISOString(),
    duration_hours: 2.0,
    status: 'confirmed',
    confirmation_status: 'confirmed',
    created_at: new Date('2024-03-25').toISOString(),
  },
  {
    id: 'b-2',
    service_id: 's-1',
    provider_id: 'user-1',
    requester_id: 'user-3',
    scheduled_start: new Date('2024-03-28T10:00:00').toISOString(),
    scheduled_end: new Date('2024-03-28T12:00:00').toISOString(),
    duration_hours: 2.0,
    status: 'completed',
    confirmation_status: 'confirmed',
    created_at: new Date('2024-03-20').toISOString(),
  },
  {
    id: 'b-3',
    service_id: 's-4',
    provider_id: 'user-4',
    requester_id: 'current-user',
    scheduled_start: new Date('2024-04-10T15:00:00').toISOString(),
    scheduled_end: new Date('2024-04-10T17:00:00').toISOString(),
    duration_hours: 2.0,
    status: 'pending',
    confirmation_status: 'pending',
    created_at: new Date('2024-03-28').toISOString(),
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: 't-1',
    to_user_id: 'current-user',
    amount: 10.0,
    transaction_type: 'signup_bonus',
    description: 'Welcome bonus for joining TimeBank',
    created_at: new Date('2024-03-01').toISOString(),
  },
  {
    id: 't-2',
    from_user_id: 'user-3',
    to_user_id: 'user-1',
    booking_id: 'b-2',
    amount: 2.0,
    transaction_type: 'service_completed',
    description: 'Payment for React & TypeScript Development Help',
    created_at: new Date('2024-03-28').toISOString(),
  },
  {
    id: 't-3',
    to_user_id: 'user-2',
    amount: 10.0,
    transaction_type: 'signup_bonus',
    description: 'Welcome bonus for joining TimeBank',
    created_at: new Date('2024-02-01').toISOString(),
  },
];

export const mockReviews: Review[] = [
  {
    id: 'r-1',
    booking_id: 'b-2',
    reviewer_id: 'user-3',
    reviewee_id: 'user-1',
    rating: 5,
    comment: 'Excellent teacher! Sarah explained React concepts very clearly and provided great examples.',
    created_at: new Date('2024-03-29').toISOString(),
  },
  {
    id: 'r-2',
    booking_id: 'b-2',
    reviewer_id: 'user-1',
    reviewee_id: 'user-3',
    rating: 5,
    comment: 'Emma was a great student, asked thoughtful questions and was very engaged.',
    created_at: new Date('2024-03-29').toISOString(),
  },
];